### ISSUE TITLE
some wrong about fork

### ISSUE THREAD

**Issue by 2021212770** [YerbaPage/MGDebugger#1]
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/55c98bff-fb93-409f-86d3-6b36d8884ad1">
This problem occurs all the time when we debug. I don't know the reason. Have you encountered it before and how to solve it

**Comment by YerbaPage** [comment]
Since we use a vLLM server to abstract away model-related dependencies (like `Torch`, `Transformers`, and `CUDA`) from the main codebase, this CUDA-related error seems unusual.

Did you happen to modify any part of the code that might have reintroduced these dependencies?
